# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutep', '0029_auto_20180220_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nutep.Container')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='nutep.DateQueryEvent')),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='info_source',
        ),
        migrations.RemoveField(
            model_name='railfreighttracking',
            name='container',
        ),
        migrations.RemoveField(
            model_name='railfreighttracking',
            name='event',
        ),
        migrations.RemoveField(
            model_name='railfreighttracking',
            name='freightdata',
        ),
        migrations.RemoveField(
            model_name='railfreighttracking',
            name='freighttracking',
        ),
        migrations.RemoveField(
            model_name='railfreighttracking',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='railfreighttracking',
            name='raildata',
        ),
        migrations.RemoveField(
            model_name='railfreighttracking',
            name='railtracking',
        ),
        migrations.DeleteModel(
            name='FreightData',
        ),
        migrations.DeleteModel(
            name='FreightTracking',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
        migrations.DeleteModel(
            name='RailData',
        ),
        migrations.DeleteModel(
            name='RailFreightTracking',
        ),
        migrations.DeleteModel(
            name='RailTracking',
        ),
    ]
