# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutep', '0030_auto_20180222_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomsProcedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure', models.CharField(max_length=50)),
                ('startdate', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('enddate', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('note', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PreOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
                ('clientguid', models.CharField(blank=True, max_length=36, null=True)),
                ('arrivaldate', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('feeddate', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deliverystopdate', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('containertrain', models.CharField(blank=True, max_length=50, null=True)),
                ('deliverypoint', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('note', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='containerstate',
            name='container',
        ),
        migrations.RemoveField(
            model_name='containerstate',
            name='event',
        ),
        migrations.AddField(
            model_name='container',
            name='releasedate',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='transport',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datequeryevent',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, '\u041f\u0440\u0435\u0434\u0432\u0430\u0440\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0435 \u0437\u0430\u044f\u0432\u043a\u0438')], null=True),
        ),
        migrations.DeleteModel(
            name='ContainerState',
        ),
        migrations.AddField(
            model_name='preorder',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='nutep.DateQueryEvent'),
        ),
        migrations.AddField(
            model_name='customsprocedure',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='nutep.Container'),
        ),
        migrations.AddField(
            model_name='container',
            name='pre_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='nutep.PreOrder'),
            preserve_default=False,
        ),
    ]
