# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutep', '0031_auto_20180225_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsprocedure',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='procedurelog',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
