# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutep', '0032_auto_20180225_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedurelog',
            name='procedure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='nutep.CustomsProcedure'),
            preserve_default=False,
        ),
    ]
