# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-23 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutep', '0035_container_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.IntegerField(choices=[(1, '\u041f\u0440\u0435\u0434\u0432\u0430\u0440\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0435 \u0437\u0430\u044f\u0432\u043a\u0438')], unique=True)),
                ('nav', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('nav', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_menu', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=100)),
                ('client_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutep.ClientService')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='dashboard_view',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companyservice',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='nutep.Company'),
        ),
        migrations.AddField(
            model_name='company',
            name='client_services',
            field=models.ManyToManyField(blank=True, related_name='companies', through='nutep.CompanyService', to='nutep.ClientService'),
        ),
        migrations.AlterUniqueTogether(
            name='companyservice',
            unique_together=set([('company', 'client_service')]),
        ),
    ]
