# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-08 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutep', '0036_auto_20180423_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='guid',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='storage',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
