# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-10 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutep', '0037_auto_20180508_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='payerguid',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
