# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-11 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutep', '0038_container_payerguid'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='payer_guid',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
