# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-11 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutep', '0039_company_payer_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_restricted',
            field=models.BooleanField(default=False),
        ),
    ]
